#!/bin/bash -x

if [ "$TEST_SUITE" == "unit" ]; then
  ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS
elif [ "$TRAVIS_SECURE_ENV_VARS" == "true" -a "$TEST_SUITE" == "integration" ]; then
  static -p 8888 &
  sleep 3
  ./node_modules/mocha/bin/mocha --harmony -R spec ./tests/integration/tests.js || true
else
  echo "Tests did not run"
  exit 1
fi
